In [5]:
import pandas as pd
import numpy as nb

dataframe = pd.read_csv('https://raw.githubusercontent.com/leonhgomes/Pandas/refs/heads/main/pokemon_data.csv')
display(dataframe)

,#,Nome,Tipo 1,Tipo 2,Vida,Ataque,Defensa,Atq Esp,Def Esp,Velocidade,Geracao,Lendario
0,1,Bulbasaur,Planta,Venenoso,45,49,49,65,65,45,1,False
1,2,Ivysaur,Planta,Venenoso,60,62,63,80,80,60,1,False
2,3,Venusaur,Planta,Venenoso,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Planta,Venenoso,80,100,123,122,120,80,1,False
4,4,Charmander,Fogo,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Pedra,Fada,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Pedra,Fada,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psiquico,Fantasma,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psiquico,Noturno,80,160,60,170,130,80,6,True
799,721,Volcanion,Fogo,Agua,80,110,120,130,90,70,6,True

In [ ]:
display(dataframe.head(10)) #Primeiras linhas

,#,Nome,Tipo 1,Tipo 2,Vida,Ataque,Defensa,Atq Esp,Def Esp,Velocidade,Geracao,Lendario
0,1,Bulbasaur,Planta,Venenoso,45,49,49,65,65,45,1,False
1,2,Ivysaur,Planta,Venenoso,60,62,63,80,80,60,1,False
2,3,Venusaur,Planta,Venenoso,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Planta,Venenoso,80,100,123,122,120,80,1,False
4,4,Charmander,Fogo,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fogo,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fogo,Voador,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fogo,Dragao,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fogo,Voador,78,104,78,159,115,100,1,False
9,7,Squirtle,Agua,NaN,44,48,65,50,64,43,1,False

In [ ]:
display(dataframe.tail(10)) #Ultimas linhas

,#,Nome,Tipo 1,Tipo 2,Vida,Ataque,Defensa,Atq Esp,Def Esp,Velocidade,Geracao,Lendario
790,714,Noibat,Voador,Dragao,40,30,35,45,40,55,6,False
791,715,Noivern,Voador,Dragao,85,70,80,97,80,123,6,False
792,716,Xerneas,Fada,NaN,126,131,95,131,98,99,6,True
793,717,Yveltal,Noturno,Voador,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragao,Terra,108,100,121,81,95,95,6,True
795,719,Diancie,Pedra,Fada,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Pedra,Fada,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psiquico,Fantasma,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psiquico,Noturno,80,160,60,170,130,80,6,True
799,721,Volcanion,Fogo,Agua,80,110,120,130,90,70,6,True

In [8]:
display(dataframe.sample(10)) #Aleatório

,#,Nome,Tipo 1,Tipo 2,Vida,Ataque,Defensa,Atq Esp,Def Esp,Velocidade,Geracao,Lendario
762,692,Clauncher,Agua,NaN,50,53,62,58,63,44,6,False
530,478,Froslass,Gelo,Fantasma,70,80,70,80,70,110,4,False
779,709,Trevenant,Fantasma,Planta,85,110,76,65,82,56,6,False
306,282,GardevoirMega Gardevoir,Psiquico,Fada,68,85,65,165,135,100,3,False
487,439,Mime Jr.,Psiquico,Fada,20,25,45,70,90,60,4,False
448,403,Shinx,Electric,NaN,45,65,34,40,34,45,4,False
775,705,Sliggoo,Dragao,NaN,68,75,53,83,113,60,6,False
452,407,Roserade,Planta,Venenoso,60,70,65,125,105,90,4,False
392,359,Absol,Noturno,NaN,65,130,60,75,60,75,3,False
729,661,Fletchling,Normal,Voador,45,50,43,40,38,62,6,False

In [ ]:
display(dataframe.shape) #Informa quantas linhas e colunas tem respectivamente

(800, 12)